### ISSUE TITLE
Android-Client-App-Sample crashes when you attempt to click Login button

### ISSUE THREAD

**Issue by john-ryles** [wso2/samples-is#194]
**Description:**

Using the Android emulator - when you attempt to tap on the login button, after you've setup your WSO2 configuration, the app crashes and gives this error:

2019-08-21 06:05:38.161 3328-3328/com.wso2is.androidsample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.wso2is.androidsample, PID: 3328
    android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
        at android.app.ContextImpl.startActivity(ContextImpl.java:952)
        at android.app.ContextImpl.startActivity(ContextImpl.java:928)
        at android.content.ContextWrapper.startActivity(ContextWrapper.java:383)
        at net.openid.appauth.AuthorizationService.performAuthorizationRequest(AuthorizationService.java:222)
        at com.wso2is.androidsample.oidc.AuthRequest.doAuth(AuthRequest.java:101)
        at com.wso2is.androidsample.activities.LoginActivity.lambda$onCreate$0$LoginActivity(LoginActivity.java:73)
        at com.wso2is.androidsample.activities.-$$Lambda$LoginActivity$Ye9sLVdMLc27I4fhpgJDHuSLhYg.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:7125)
        at android.view.View.performClickInternal(View.java:7102)
        at android.view.View.access$3400(View.java:801)
        at android.view.View$PerformClick.run(View.java:27301)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7319)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:934)
2019-08-21 06:05:38.170 3328-3328/com.wso2is.androidsample I/Process: Sending signal. PID: 3328 SIG: 9

**Steps to reproduce:**
Download repo and run in Android Studio and add WSO2 configuration in config.json

**Comment by Manukam** [comment]
Looks like the app has some issues with the latest android versions. Try with Android N (7)
